schema_version = "1.0.0"
# Change the values according to your extension
id = "Quick Nodes"
version = "1.0"
name = "Quick Nodes"
tagline = "Quickly add Nodes without using the Keyboard and the Add Menu. Search and Favorites available to speed up workflow."
maintainer = "Lloyd DeAlmeida"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/digim0nk/blenderQuickNodes"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["nodes"]

blender_version_min = "5.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
